Repository AY2223S2-CS2113-W12-4/tp, pull requests merged in 2023-04, with the labels that each got.

#141 D issues
  src/main/java/seedu/moviemate/command/RemoveListCommand.java
  src/main/java/seedu/moviemate/command/SeeDetailCommand.java
  src/main/java/seedu/moviemate/movie/MovieList.java
  src/main/java/seedu/moviemate/movie/WatchedList.java
Labels: type.Functionality, priority.should-have

#142 Add random movie
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/moviemate/command/AddToWatchListCommand.java
  src/main/java/seedu/moviemate/command/RandomMovieCommand.java
  src/main/java/seedu/moviemate/parser/Parser.java
  src/main/java/seedu/moviemate/storage/MovieDatabase.java
  src/main/java/seedu/moviemate/ui/Ui.java
Labels: enhancement

#140 More documentation
  docs/PUMLFiles/Review/review_class.puml
  docs/PUMLFiles/Review/review_sequence.puml
  docs/PUMLFiles/style.puml
  docs/README.md
Labels: documentation

#153 Update ug
  docs/UserGuide.md
  src/main/java/seedu/moviemate/command/AddToWatchListCommand.java
  src/main/java/seedu/moviemate/command/AddWatchedListCommand.java
  src/main/java/seedu/moviemate/command/ListCommand.java
  src/main/java/seedu/moviemate/command/RemoveListCommand.java
  src/main/java/seedu/moviemate/command/SeeDetailCommand.java
  src/main/java/seedu/moviemate/movie/MovieList.java
  src/main/java/seedu/moviemate/parser/Parser.java
  src/main/java/seedu/moviemate/ui/Ui.java
Labels: documentation

#154 More documentation
  docs/.idea/.gitignore
  docs/.idea/misc.xml
  docs/.idea/modules.xml
  docs/.idea/vcs.xml
  docs/DeveloperGuide.md
  docs/PUMLFiles/Architecture.PUML
  docs/PUMLFiles/Architecture.png
  docs/PUMLFiles/ExampleSequence.PUML
  docs/PUMLFiles/ExampleSequence.png
  docs/PUMLFiles/MainComponents.PUML
  docs/PUMLFiles/MovieClass.png
  docs/PUMLFiles/MovieClass.puml
  docs/PUMLFiles/MovieList/movielist_class.puml
  docs/PUMLFiles/style.puml
  docs/SetupGuide.md
  docs/_config.yml
  src/main/java/seedu/moviemate/command/AddReviewCommand.java
  src/main/java/seedu/moviemate/command/AddToWatchListCommand.java
  src/main/java/seedu/moviemate/command/AddWatchedListCommand.java
  src/main/java/seedu/moviemate/command/Command.java
  src/main/java/seedu/moviemate/command/DeleteReviewCommand.java
  src/main/java/seedu/moviemate/command/ExitCommand.java
  src/main/java/seedu/moviemate/command/FilterCommand.java
  src/main/java/seedu/moviemate/command/HelpCommand.java
  src/main/java/seedu/moviemate/command/ListCommand.java
  src/main/java/seedu/moviemate/command/RandomMovieCommand.java
  src/main/java/seedu/moviemate/command/RemoveListCommand.java
  src/main/java/seedu/moviemate/command/SeeDetailCommand.java
  src/main/java/seedu/moviemate/command/ViewReviewCommand.java
  src/main/java/seedu/moviemate/command/WatchListCommand.java
Labels: documentation

#156 Zhanhong ppp
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/_config.yml
  docs/team/choongzhanhong.md
  docs/team/zhanhong.md
Labels: documentation
