Repository AY2223S2-CS2113-W12-4/tp, pull requests merged in 2023-03, with the labels that each got.

#8 Basic Framework update
  .gitignore
  README.md
  src/main/java/Movie.java
Labels: must-have

#28 Add Movie Database
  src/main/java/Movie.java
  src/main/java/MovieDatabase.java
  src/main/java/MovieList.java
  src/main/java/MovieMate.java
  src/main/java/ReadCSVFile.java
  src/main/java/ToWatchList.java
  src/main/java/WatchedList.java
Labels: type.Functionality, priority.should-have

#43 Add filter command
  src/main/java/Movie.java
  src/main/java/MovieList.java
  src/main/java/MovieMate.java
Labels: type.Story, priority.should-have

#45 Review
  src/main/java/Movie.java
  src/main/java/MovieEntry.java
  src/main/java/MovieList.java
  src/main/java/MovieMate.java
  src/main/java/Review.java
  src/main/java/WatchedList.java
Labels: type.Story, priority.should-have

#48 Add developer guide for movie list
  docs/DeveloperGuide.md
  docs/PUMLFiles/MovieList/movielist1.png
  docs/PUMLFiles/MovieList/movielist2.png
  docs/PUMLFiles/MovieList/movielist_class.puml
  docs/PUMLFiles/MovieList/movielist_sequence.puml
  src/main/java/MovieMate.java
Labels: documentation

#56 Add seedetail
  src/main/java/MovieList.java
  src/main/java/MovieMate.java
  src/main/java/Ui.java
  src/test/java/ReviewTest.java
Labels: enhancement, priority.should-have

#53 Jared3
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/Load.java
  src/main/java/MovieList.java
  src/main/java/MovieMate.java
  src/main/java/Save.java
Labels: priority.must-have
